const { chromium } = require('playwright');
const id = 'proj_1777128165822_6acnqx';
const url = `https://playcools.top/webgl/${id}/index.html`;
(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  const ctx = await browser.newContext({ viewport: { width: 750, height: 1334 } });
  const page = await ctx.newPage();
  const lines = [];
  page.on('console', m => { const t = m.text(); if (/__PHASE__|GameFlow|phase|joystick|GFM_AutoPlay|VisualGuide|error/i.test(t)) lines.push(`[${m.type()}] ${t.slice(0,200)}`); });
  page.on('pageerror', e => lines.push('PE: '+String(e).slice(0,220)));
  await page.goto(url, { waitUntil: 'networkidle', timeout: 60000 }).catch(e=>lines.push('goto:'+e.message.slice(0,120)));
  await page.waitForTimeout(8000);
  await page.screenshot({ path: '/tmp/preview-shots/proj_1777128165822_6acnqx-noauto-t8.png' });
  await page.waitForTimeout(15000);
  await page.screenshot({ path: '/tmp/preview-shots/proj_1777128165822_6acnqx-noauto-t23.png' });
  const gs = await page.evaluate(() => window.__gameState ? JSON.parse(JSON.stringify(window.__gameState)) : null).catch(()=>null);
  await page.waitForTimeout(20000);
  await page.screenshot({ path: '/tmp/preview-shots/proj_1777128165822_6acnqx-noauto-t43.png' });
  const gs2 = await page.evaluate(() => window.__gameState ? JSON.parse(JSON.stringify(window.__gameState)) : null).catch(()=>null);
  console.log('GS-t23:', JSON.stringify(gs).slice(0, 600));
  console.log('GS-t43:', JSON.stringify(gs2).slice(0, 600));
  console.log('LOGS:'); lines.slice(-30).forEach(l=>console.log(' ',l));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
