const templates = [
  {
    name: '空白项目',
    nodes: [],
    edges: [],
    entities: [],
    phases: [],
  },
  {
    name: 'SLG 建造防御 (V4)',
    nodes: [],
    edges: [],
    entities: [
      {
        name: 'Ground',
        label: '地面',
        template: 'Static',
        visual: { shape: 'Ground', scale: '40×1×40', color: '(0.35,0.25,0.15)', position: '(0,0,0)' },
        spawn: { condition: 'phase:1', style: 'instant', persistent: true },
        trigger: { type: 'none' },
        actions: [],
        behavior: {},
      },
      {
        name: 'Player',
        label: '玩家角色',
        template: 'PlayerController',
        visual: { shape: 'Capsule', scale: '1×2×1', color: '(0.2,0.6,0.9)', position: '(0,1,0)' },
        spawn: { condition: 'phase:1', style: 'popUp', persistent: true },
        trigger: { type: 'none' },
        actions: [],
        behavior: { moveSpeed: 5 },
      },
      {
        name: 'ConveyorBelt',
        label: '传送带',
        template: 'Buildable',
        visual: { shape: 'Cube', scale: '4×0.3×1', color: '(0.5,0.5,0.55)', position: '(3,0,2)' },
        spawn: { condition: 'phase:1', style: 'blueprint', persistent: true },
        trigger: { type: 'proximity', params: { radius: 2, cost: { gold: 1 } }, once: true },
        actions: [
          { type: 'playAnim', params: { name: 'buildProgress', duration: 1.5 } },
          { type: 'setState', params: { state: 'working' } },
          { type: 'activate', params: { targets: ['WoodSpawner'] } },
        ],
        behavior: { buildTime: 1.5, onBuilt: ['activate:WoodSpawner'] },
      },
      {
        name: 'WoodSpawner',
        label: '木材生成器',
        template: 'Spawner',
        visual: { shape: 'Cube', scale: '1×1×1', color: '(0.4,0.25,0.1)', position: '(6,0.5,2)' },
        spawn: { condition: 'entity:ConveyorBelt.state==built', style: 'fadeIn', persistent: true },
        trigger: { type: 'auto' },
        actions: [],
        behavior: { spawnEntity: 'WoodLog', spawnInterval: 3, maxAlive: 5 },
      },
      {
        name: 'Turret',
        label: '炮塔',
        template: 'Shooter',
        visual: { shape: 'Cylinder', scale: '1×2×1', color: '(0.6,0.6,0.6)', position: '(-3,1,5)' },
        spawn: { condition: 'phase:3', style: 'blueprint', persistent: true },
        trigger: { type: 'proximity', params: { radius: 2, cost: { wood: 3 } }, once: true },
        actions: [
          { type: 'playAnim', params: { name: 'buildProgress', duration: 2 } },
          { type: 'setState', params: { state: 'active' } },
        ],
        behavior: { fireRate: 1.5, damage: 10, range: 8, targetTag: 'enemy', projectile: 'Arrow' },
      },
      {
        name: 'Enemy',
        label: '敌人',
        template: 'Mover',
        visual: { shape: 'Capsule', scale: '1×1.5×1', color: '(0.8,0.2,0.2)', position: '(0,0.75,-15)' },
        spawn: { condition: 'phase:3', style: 'instant', persistent: false },
        trigger: { type: 'auto' },
        actions: [],
        behavior: { moveSpeed: 2, moveTarget: 'Base', hp: 30 },
      },
    ],
    phases: [
      { id: 1, name: '建造传送带', activate: ['Ground', 'Player', 'ConveyorBelt'], endCondition: 'entity:ConveyorBelt.state==built', guide: '走到传送带蓝图处建造' },
      { id: 2, name: '资源收集', activate: ['WoodSpawner'], endCondition: 'resource:wood>=3', guide: '收集木材' },
      { id: 3, name: '防御作战', activate: ['Turret', 'Enemy'], endCondition: 'entity:Enemy.count==0', guide: '建造炮塔击败敌人' },
    ],
    globalSettings: {
      gameType: 'slg',
      cameraProjection: 'orthographic',
      cameraAngle: 'topDown45',
      backgroundColor: '(0.5,0.8,1)',
    },
  },
  {
    name: '跑酷闯关 (V4)',
    nodes: [],
    edges: [],
    entities: [
      {
        name: 'Ground',
        label: '跑道',
        template: 'Static',
        visual: { shape: 'Cube', scale: '4×0.5×100', color: '(0.3,0.3,0.35)', position: '(0,0,0)' },
        spawn: { condition: 'phase:1', style: 'instant', persistent: true },
        trigger: { type: 'none' },
        actions: [],
        behavior: {},
      },
      {
        name: 'Runner',
        label: '跑酷角色',
        template: 'PlayerController',
        visual: { shape: 'Capsule', scale: '0.8×1.5×0.8', color: '(0.2,0.7,0.3)', position: '(0,1,-5)' },
        spawn: { condition: 'phase:1', style: 'instant', persistent: true },
        trigger: { type: 'none' },
        actions: [],
        behavior: { moveSpeed: 8 },
      },
      {
        name: 'Obstacle',
        label: '障碍物',
        template: 'Damageable',
        visual: { shape: 'Cube', scale: '2×2×0.5', color: '(0.8,0.3,0.2)', position: '(0,1,10)' },
        spawn: { condition: 'phase:1', style: 'instant', persistent: false },
        trigger: { type: 'none' },
        actions: [],
        behavior: { hp: 1 },
      },
      {
        name: 'Coin',
        label: '金币',
        template: 'Collectible',
        visual: { shape: 'Sphere', scale: '0.5×0.5×0.5', color: '(1,0.85,0)', position: '(1,1.5,8)' },
        spawn: { condition: 'phase:1', style: 'instant', persistent: false },
        trigger: { type: 'proximity', params: { radius: 1.5 }, once: true },
        actions: [
          { type: 'addResource', params: { resource: 'score', amount: 10 } },
        ],
        behavior: {},
      },
    ],
    phases: [
      { id: 1, name: '起跑', activate: ['Ground', 'Runner', 'Obstacle', 'Coin'], endCondition: 'position:Runner.z>=90', guide: '左右滑动躲避障碍' },
      { id: 2, name: '终点', activate: [], endCondition: 'tap:CTA', guide: '点击下载' },
    ],
    globalSettings: {
      gameType: 'runner',
      cameraProjection: 'perspective',
      cameraAngle: 'sideView',
      backgroundColor: '(0.4,0.7,1)',
    },
  },
];

export default templates;
