import JSZip from 'jszip';

export function importFromJSON(json) {
  return buildNodesFromJSON(json, {});
}

function buildNodesFromJSON(json, modelDataMap) {
  const nodes = [];
  const edges = [];
  let entities = [];
  let phases = [];
  let globalSettings = {};

  // V4: entity-driven import
  {
    entities = json.entities || [];
    phases = json.phases || [];
    globalSettings = json.globalSettings || {};

    // Generate phase nodes
    (json.phases || []).forEach((p, i) => {
      nodes.push({
        id: `phase_${p.id || i + 1}`,
        type: 'phaseNode',
        position: { x: 50, y: i * 300 },
        data: {
          name: p.name || `Phase ${p.id || i + 1}`,
          activate: p.activate || [],
          endCondition: p.endCondition || '',
          guide: p.guide || '',
          camera: p.camera || {},
        },
      });
    });

    // Entity nodes will be auto-generated by App.jsx's generateEntityNodesAndEdges
    // when entities state is set

    if (json.annotations) {
      json.annotations.forEach((ann) => {
        nodes.push({
          id: ann.id,
          type: 'noteNode',
          position: { x: ann.x, y: ann.y },
          data: { text: ann.text || '' },
        });
      });
    }

    return { nodes, edges, entities, phases, globalSettings, projectName: json.project || '未命名项目' };
  }


}

export async function readFileAsJSON(file) {
  if (file.name.endsWith('.zip')) {
    const zip = await JSZip.loadAsync(file);
    const jsonFile = zip.file('blueprint.json');
    if (!jsonFile) throw new Error('zip 中未找到 blueprint.json');
    const jsonText = await jsonFile.async('string');
    const json = JSON.parse(jsonText);
    const modelDataMap = {};
    const modelFiles = zip.file(/^models\//);
    for (const mf of modelFiles) {
      if (!mf.dir) {
        const base64 = await mf.async('base64');
        modelDataMap[mf.name] = `data:application/octet-stream;base64,${base64}`;
      }
    }
    const result = buildNodesFromJSON(json, modelDataMap);
    return { __parsed: true, ...result };
  }

  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      try { resolve(JSON.parse(e.target.result)); }
      catch (err) { reject(new Error('无效的 JSON 文件')); }
    };
    reader.onerror = () => reject(new Error('读取文件失败'));
    reader.readAsText(file);
  });
}
